apiVersion: 1.1

storage:
  name: simple
  type: local

releases:
  default:
    chart: bitnami/nginx
    chartVersion: 14.2.1
  jekyll:
    chart: bitnami/nginx
    chartVersion: 14.2.1
    values:
      cloneStaticSiteFromGit:
        enabled: true
        repository: https://github.com/jekyll/jekyll
        branch: gh-pages

repositories:
  bitnami: https://charts.bitnami.com/bitnami
