name: Deploy docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yaml
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-cache-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-
            fontawesome_
            mike
            pydown-extensions
      - run: pip install mkdocs mkdocs-material mkdocs-autolinks-plugin mkdocs-drawio-file mkdocs-git-revision-date-localized-plugin mkdocs-table-reader-plugin fontawesome_markdown mike pymdown-extensions
      - run: mkdocs gh-deploy --force
